services:
  - type: web
    name: ml-model-backend
    env: python
    branch: main
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
